import type { MarketBookmarkExcluded } from '@/shared/market-seed-types'

export const MARKET_BOOKMARK_EXCLUDED = [
  {
    seedId: "app_open_qq_com",
    bookmarkTitle: "上架/更新编辑页",
    bookmarkUrl: "https://app.open.qq.com/p/basic/distribution/update/edit?appId=1112501604",
    inclusionStatus: "excluded",
    exclusionReason: "Private project console.",
    siteHostname: "app.open.qq.com",
    isFromBookmarks: true,
  },
  {
    seedId: "autocatalogarchive_com",
    bookmarkTitle: "Over 55.000 car brochures from brands around the world",
    bookmarkUrl: "https://autocatalogarchive.com/",
    inclusionStatus: "excluded",
    exclusionReason: "Archive site with low relevance to the current market scope.",
    siteHostname: "autocatalogarchive.com",
    isFromBookmarks: true,
  },
  {
    seedId: "cloud_mongodb_com",
    bookmarkTitle: "artmind Overview | Cloud: MongoDB Cloud",
    bookmarkUrl: "https://cloud.mongodb.com/v2/69af790af0f890256658c274#/clusters/detail/artmind",
    inclusionStatus: "excluded",
    exclusionReason: "Private project console.",
    siteHostname: "cloud.mongodb.com",
    isFromBookmarks: true,
  },
  {
    seedId: "co_yes_vg",
    bookmarkTitle: "YesCode",
    bookmarkUrl: "https://co.yes.vg/login",
    inclusionStatus: "excluded",
    exclusionReason: "Login page for a personal workspace; not suitable as a market asset.",
    siteHostname: "co.yes.vg",
    isFromBookmarks: true,
  },
  {
    seedId: "console_authing_cn",
    bookmarkTitle: "用户列表",
    bookmarkUrl: "https://console.authing.cn/console/69b0fdad323d211bd63353c7/user",
    inclusionStatus: "excluded",
    exclusionReason: "Private project console.",
    siteHostname: "console.authing.cn",
    isFromBookmarks: true,
  },
  {
    seedId: "dev_dcloud_net_cn",
    bookmarkTitle: "账号信息",
    bookmarkUrl: "https://dev.dcloud.net.cn/pages/user/info",
    inclusionStatus: "excluded",
    exclusionReason: "Account console page.",
    siteHostname: "dev.dcloud.net.cn",
    isFromBookmarks: true,
  },
  {
    seedId: "dytt012_cc",
    bookmarkTitle: "电影天堂 | 电影天堂网最新电影大全",
    bookmarkUrl: "https://dytt012.cc/",
    inclusionStatus: "excluded",
    exclusionReason: "Streaming resource site with high copyright risk.",
    siteHostname: "dytt012.cc",
    isFromBookmarks: true,
  },
  {
    seedId: "fmhy_net",
    bookmarkTitle: "Welcome • freemediaheckyeah",
    bookmarkUrl: "https://fmhy.net/",
    inclusionStatus: "excluded",
    exclusionReason: "Mixed aggregation site with unstable provenance.",
    siteHostname: "fmhy.net",
    isFromBookmarks: true,
  },
  {
    seedId: "github_com",
    bookmarkTitle: "OAuth application authorized",
    bookmarkUrl: "https://github.com/login/oauth/authorize",
    inclusionStatus: "excluded",
    exclusionReason: "OAuth flow page, not a reusable tool asset.",
    siteHostname: "github.com",
    isFromBookmarks: true,
  },
  {
    seedId: "hyper3d_ai",
    bookmarkTitle: "AI Doraemon cartoon character. simple geometry, game-ready, character, symmetric geometry. 3D 模型 | Nirvazure 创建的逼真 Doraemon cartoon character. simple geometry, game-ready, character, symmetric geom...",
    bookmarkUrl: "https://hyper3d.ai/rodin/51fdd4a4-fa1e-4e1e-aaf0-114d0370951b",
    inclusionStatus: "excluded",
    exclusionReason: "Project-specific workspace; keep the product homepage only.",
    siteHostname: "hyper3d.ai",
    isFromBookmarks: true,
  },
  {
    seedId: "landonorris_com",
    bookmarkTitle: "2025 McLaren Formula 1 Driver — Lando Norris",
    bookmarkUrl: "https://landonorris.com/?trk=public_post_main-feed-card-text",
    inclusionStatus: "excluded",
    exclusionReason: "Personal interest content; low relevance to the market asset pool.",
    siteHostname: "landonorris.com",
    isFromBookmarks: true,
  },
  {
    seedId: "mj_superx360_com",
    bookmarkTitle: "Midjourney官网",
    bookmarkUrl: "https://mj.superx360.com/",
    inclusionStatus: "excluded",
    exclusionReason: "Unofficial Midjourney mirror / redirect site.",
    siteHostname: "mj.superx360.com",
    isFromBookmarks: true,
  },
  {
    seedId: "mp_weixin_qq_com",
    bookmarkTitle: "微信公众平台",
    bookmarkUrl: "https://mp.weixin.qq.com/s?__biz=MjM5MDA2MTI1MA==&mid=2649117118&idx=1&sn=1d98d7282d82390f629ec3678ff6889c&chksm=be587613892fff05e8130edb3857e8b1d07c3ce6712f8c781d353b4fdc40ee5a313fde9e29a3&scene=27",
    inclusionStatus: "excluded",
    exclusionReason: "Single article page; not a stable reusable asset.",
    siteHostname: "mp.weixin.qq.com",
    isFromBookmarks: true,
  },
  {
    seedId: "open_tencent_com",
    bookmarkTitle: "腾讯开放平台beta|开放成就梦想",
    bookmarkUrl: "https://open.tencent.com/",
    inclusionStatus: "excluded",
    exclusionReason: "Platform portal with weak value for the current market surface.",
    siteHostname: "open.tencent.com",
    isFromBookmarks: true,
  },
  {
    seedId: "paywallbuster_com",
    bookmarkTitle: "Remove Paywalls from News Articles Instantly | PaywallBuster",
    bookmarkUrl: "https://paywallbuster.com/",
    inclusionStatus: "excluded",
    exclusionReason: "Paywall bypassing tool with compliance risk.",
    siteHostname: "paywallbuster.com",
    isFromBookmarks: true,
  },
  {
    seedId: "snapany_com",
    bookmarkTitle: "万能视频图片解析下载 - SnapAny",
    bookmarkUrl: "https://snapany.com/zh",
    inclusionStatus: "excluded",
    exclusionReason: "Video downloading site with copyright/compliance risk.",
    siteHostname: "snapany.com",
    isFromBookmarks: true,
  },
  {
    seedId: "stickerapp_com",
    bookmarkTitle: "Editor",
    bookmarkUrl: "https://stickerapp.com/editor/new_product?productItem=%7B%22productFamilyName%22%3A%22custom_sticker%22%2C%22productName%22%3A%22die_cut%22%2C%22attributes%22%3A%7B%22delivery%22%3A%22single%22%2C%22sheet_type%22%3A%22single%22%2C%22laminate%22%3A%22glossy_uv%22%2C%22material%22%3A%22white%22%2C%22sheet_name%22%3A%22path%22%2C%22quantity%22%3A29%2C%22market%22%3A%22us%22%2C%22imperial_units%22%3Atrue%2C%22width_mm%22%3A51%2C%22height_mm%22%3A51%2C%22size%22%3A%222%5C%22+x+2%5C%22%22%7D%7D&file=%7B%22fileapp_id%22%3A%22480ce377-e4ee-4cd0-914b-421018f5fcda%22%2C%22name%22%3A%22impress+%28173%29.jpeg.jpg%22%2C%22size%22%3A884835%2C%22thumb_url%22%3A%22https%3A%2F%2Ffileapp-ap-northeast-1.s3.ap-northeast-1.amazonaws.com%2Fthumbs%2F480ce377-e4ee-4cd0-914b-421018f5fcda_thumb.png%22%2C%22width%22%3A640%2C%22height%22%3A1136%2C%22fileapp_region%22%3A%22ap-northeast-1%22%2C%22upload_id%22%3A0%2C%22background%22%3A%22%23fef2fe%22%7D",
    inclusionStatus: "excluded",
    exclusionReason: "Editor state page, not a generic reusable asset.",
    siteHostname: "stickerapp.com",
    isFromBookmarks: true,
  },
  {
    seedId: "stitch_withgoogle_com",
    bookmarkTitle: "Stitch - Projects",
    bookmarkUrl: "https://stitch.withgoogle.com/projects/1123718445028830435",
    inclusionStatus: "excluded",
    exclusionReason: "Project-specific page; keep the product homepage only.",
    siteHostname: "stitch.withgoogle.com",
    isFromBookmarks: true,
  },
  {
    seedId: "www_16personalities_com",
    bookmarkTitle: "Career Paths | INFJ Personality (Advocate) | 16Personalities",
    bookmarkUrl: "https://www.16personalities.com/infj-careers",
    inclusionStatus: "excluded",
    exclusionReason: "Personality content page, not a tool/resource asset.",
    siteHostname: "www.16personalities.com",
    isFromBookmarks: true,
  },
  {
    seedId: "www_bestvideow_com",
    bookmarkTitle: "免费视频解析下载_抖音，B站(哔哩哔哩)视频解析下载工具 - Best Video下载器",
    bookmarkUrl: "https://www.bestvideow.com/",
    inclusionStatus: "excluded",
    exclusionReason: "Video downloading site with copyright/compliance risk.",
    siteHostname: "www.bestvideow.com",
    isFromBookmarks: true,
  },
  {
    seedId: "www_datatool_vip",
    bookmarkTitle: "适用于任何网站的快速视频下载器 - DataTool.vip",
    bookmarkUrl: "https://www.datatool.vip/",
    inclusionStatus: "excluded",
    exclusionReason: "Video downloading site with copyright/compliance risk.",
    siteHostname: "www.datatool.vip",
    isFromBookmarks: true,
  },
  {
    seedId: "www_meshy_ai",
    bookmarkTitle: "工作区",
    bookmarkUrl: "https://www.meshy.ai/zh/workspace",
    inclusionStatus: "excluded",
    exclusionReason: "Workspace page; keep the product homepage only.",
    siteHostname: "www.meshy.ai",
    isFromBookmarks: true,
  },
  {
    seedId: "www_nmdvd_cc",
    bookmarkTitle: "农民影视-最新电影,vip热播剧在线观看,免费影视大全",
    bookmarkUrl: "https://www.nmdvd.cc/",
    inclusionStatus: "excluded",
    exclusionReason: "Streaming resource site with high copyright risk.",
    siteHostname: "www.nmdvd.cc",
    isFromBookmarks: true,
  },
  {
    seedId: "www_seedhub_cc",
    bookmarkTitle: "SeedHub | 影视&动漫分享",
    bookmarkUrl: "https://www.seedhub.cc/",
    inclusionStatus: "excluded",
    exclusionReason: "Streaming/share site with high copyright risk.",
    siteHostname: "www.seedhub.cc",
    isFromBookmarks: true,
  },
  {
    seedId: "www_sunozh_com",
    bookmarkTitle: "Suno Ai音乐中文版 - 在线一键创作高质量的Ai音乐软件",
    bookmarkUrl: "https://www.sunozh.com/",
    inclusionStatus: "excluded",
    exclusionReason: "Unofficial mirror; keep the official Suno site only.",
    siteHostname: "www.sunozh.com",
    isFromBookmarks: true,
  },
  {
    seedId: "www_sxrsks_cn",
    bookmarkTitle: "陕西人事考试网",
    bookmarkUrl: "https://www.sxrsks.cn/website/home.aspx",
    inclusionStatus: "excluded",
    exclusionReason: "Exam information site; low relevance to the current market scope.",
    siteHostname: "www.sxrsks.cn",
    isFromBookmarks: true,
  },
  {
    seedId: "www_workout_cool",
    bookmarkTitle: "Build Your Perfect Workout | Workout Cool",
    bookmarkUrl: "https://www.workout.cool/",
    inclusionStatus: "excluded",
    exclusionReason: "Workout planner; lower relevance to the current product scope.",
    siteHostname: "www.workout.cool",
    isFromBookmarks: true,
  },
  {
    seedId: "yqydarkrai_artmind_hf_space",
    bookmarkTitle: "yqydarkrai-artmind.hf.space",
    bookmarkUrl: "https://yqydarkrai-artmind.hf.space/",
    inclusionStatus: "excluded",
    exclusionReason: "Personal demo project; not suitable for the shared market pool.",
    siteHostname: "yqydarkrai-artmind.hf.space",
    isFromBookmarks: true,
  },
] satisfies readonly MarketBookmarkExcluded[]
