import type { MarketBookmarkExcluded } from '@/shared/market-seed-types'

export const MARKET_BOOKMARK_EXCLUDED = [
  {
    seedId: 'app_open_qq_com',
    bookmarkTitle: 'QQ Open Platform edit page',
    bookmarkUrl: 'https://app.open.qq.com/p/basic/distribution/update/edit?appId=1112501604',
    inclusionStatus: 'excluded',
    exclusionReason: 'Private project console.',
    siteHostname: 'app.open.qq.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'autocatalogarchive_com',
    bookmarkTitle: 'Over 55,000 car brochures from brands around the world',
    bookmarkUrl: 'https://autocatalogarchive.com/',
    inclusionStatus: 'excluded',
    exclusionReason: 'Archive site with low relevance to the current market scope.',
    siteHostname: 'autocatalogarchive.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'cloud_mongodb_com',
    bookmarkTitle: 'artmind Overview | MongoDB Cloud',
    bookmarkUrl: 'https://cloud.mongodb.com/v2/69af790af0f890256658c274#/clusters/detail/artmind',
    inclusionStatus: 'excluded',
    exclusionReason: 'Private project console.',
    siteHostname: 'cloud.mongodb.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'co_yes_vg',
    bookmarkTitle: 'YesCode login',
    bookmarkUrl: 'https://co.yes.vg/login',
    inclusionStatus: 'excluded',
    exclusionReason: 'Login page for a personal workspace; not suitable as a market asset.',
    siteHostname: 'co.yes.vg',
    isFromBookmarks: true,
  },
  {
    seedId: 'dev_dcloud_net_cn',
    bookmarkTitle: 'DCloud account info',
    bookmarkUrl: 'https://dev.dcloud.net.cn/pages/user/info',
    inclusionStatus: 'excluded',
    exclusionReason: 'Account console page.',
    siteHostname: 'dev.dcloud.net.cn',
    isFromBookmarks: true,
  },
  {
    seedId: 'fmhy_net',
    bookmarkTitle: 'Welcome - freemediaheckyeah',
    bookmarkUrl: 'https://fmhy.net/',
    inclusionStatus: 'excluded',
    exclusionReason: 'Mixed aggregation site with unstable provenance.',
    siteHostname: 'fmhy.net',
    isFromBookmarks: true,
  },
  {
    seedId: 'github_com',
    bookmarkTitle: 'OAuth application authorized',
    bookmarkUrl: 'https://github.com/login/oauth/authorize',
    inclusionStatus: 'excluded',
    exclusionReason: 'OAuth flow page, not a reusable tool asset.',
    siteHostname: 'github.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'hyper3d_ai',
    bookmarkTitle: 'Hyper3D project workspace',
    bookmarkUrl: 'https://hyper3d.ai/rodin/51fdd4a4-fa1e-4e1e-aaf0-114d0370951b',
    inclusionStatus: 'excluded',
    exclusionReason: 'Project-specific workspace; keep the product homepage only.',
    siteHostname: 'hyper3d.ai',
    isFromBookmarks: true,
  },
  {
    seedId: 'landonorris_com',
    bookmarkTitle: '2025 McLaren Formula 1 Driver - Lando Norris',
    bookmarkUrl: 'https://landonorris.com/?trk=public_post_main-feed-card-text',
    inclusionStatus: 'excluded',
    exclusionReason: 'Personal interest content; low relevance to the market asset pool.',
    siteHostname: 'landonorris.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'paywallbuster_com',
    bookmarkTitle: 'Remove Paywalls from News Articles Instantly | PaywallBuster',
    bookmarkUrl: 'https://paywallbuster.com/',
    inclusionStatus: 'excluded',
    exclusionReason: 'Paywall bypassing tool with compliance risk.',
    siteHostname: 'paywallbuster.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'stickerapp_com',
    bookmarkTitle: 'StickerApp editor state page',
    bookmarkUrl:
      'https://stickerapp.com/editor/new_product?productItem=%7B%22productFamilyName%22%3A%22custom_sticker%22%2C%22productName%22%3A%22die_cut%22%2C%22attributes%22%3A%7B%22delivery%22%3A%22single%22%2C%22sheet_type%22%3A%22single%22%2C%22laminate%22%3A%22glossy_uv%22%2C%22material%22%3A%22white%22%2C%22sheet_name%22%3A%22path%22%2C%22quantity%22%3A29%2C%22market%22%3A%22us%22%2C%22imperial_units%22%3Atrue%2C%22width_mm%22%3A51%2C%22height_mm%22%3A51%2C%22size%22%3A%222%5C%22+x+2%5C%22%22%7D%7D&file=%7B%22fileapp_id%22%3A%22480ce377-e4ee-4cd0-914b-421018f5fcda%22%2C%22name%22%3A%22impress+%28173%29.jpeg.jpg%22%2C%22size%22%3A884835%2C%22thumb_url%22%3A%22https%3A%2F%2Ffileapp-ap-northeast-1.s3.ap-northeast-1.amazonaws.com%2Fthumbs%2F480ce377-e4ee-4cd0-914b-421018f5fcda_thumb.png%22%2C%22width%22%3A640%2C%22height%22%3A1136%2C%22fileapp_region%22%3A%22ap-northeast-1%22%2C%22upload_id%22%3A0%2C%22background%22%3A%22%23fef2fe%22%7D',
    inclusionStatus: 'excluded',
    exclusionReason: 'Editor state page, not a generic reusable asset.',
    siteHostname: 'stickerapp.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'stitch_withgoogle_com',
    bookmarkTitle: 'Stitch project page',
    bookmarkUrl: 'https://stitch.withgoogle.com/projects/1123718445028830435',
    inclusionStatus: 'excluded',
    exclusionReason: 'Project-specific page; keep the product homepage only.',
    siteHostname: 'stitch.withgoogle.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'www_16personalities_com',
    bookmarkTitle: 'Career Paths | INFJ Personality (Advocate) | 16Personalities',
    bookmarkUrl: 'https://www.16personalities.com/infj-careers',
    inclusionStatus: 'excluded',
    exclusionReason: 'Personality content page, not a tool/resource asset.',
    siteHostname: 'www.16personalities.com',
    isFromBookmarks: true,
  },
  {
    seedId: 'www_workout_cool',
    bookmarkTitle: 'Build Your Perfect Workout | Workout Cool',
    bookmarkUrl: 'https://www.workout.cool/',
    inclusionStatus: 'excluded',
    exclusionReason: 'Workout planner; lower relevance to the current product scope.',
    siteHostname: 'www.workout.cool',
    isFromBookmarks: true,
  },
  {
    seedId: 'yqydarkrai_artmind_hf_space',
    bookmarkTitle: 'yqydarkrai-artmind.hf.space',
    bookmarkUrl: 'https://yqydarkrai-artmind.hf.space/',
    inclusionStatus: 'excluded',
    exclusionReason: 'Personal demo project; not suitable for the shared market pool.',
    siteHostname: 'yqydarkrai-artmind.hf.space',
    isFromBookmarks: true,
  },
] satisfies readonly MarketBookmarkExcluded[]
