export const PAGE_COPY = {
  analysis: {
    title: 'DoraPocket',
    subtitle: '像哆啦A梦一样，在你开口时先替你挑出这次最该用的工具。',
    promptSuggestion: '帮我找一个最好用的 PDF 压缩工具',
    promptPlaceholder: '试试：帮我找一个最好用的 PDF 压缩工具',
  },
  market: {
    title: '道具库',
    subtitle: '发现好工具、提交好工具，一起把 DoraPocket 的工具知识库养起来。',
    searchPlaceholder: '搜索工具、能力、标签或场景…',
    submitAction: '提交工具',
    collectAction: '收进口袋',
    openAction: '打开工具',
    reviewAction: '补充体验',
    reviewSupplementScore: '补充评分',
    updateReviewAction: '更新体验',
    builtinSection: '内置道具',
    pocketSection: '我的口袋',
    removeFromPocketAction: '移出口袋',
    pocketEmptyTitle: '口袋里还没有工具',
    pocketEmptyDescription: '先去发现道具，把你以后还想再打开的工具收进来。',
    pocketEmptyAction: '去发现道具',
    discoverScopeLabel: '全部道具',
    discoverSection: '发现',
    noSearchResult: '没有找到符合当前搜索条件的工具。',
    reviewDrawerTitle: '这次这个工具好用吗？',
    reviewDrawerSubtitle: '告诉 DoraPocket 它为什么适合，或者为什么这次不该先掏出来。',
    reviewVoteTitle: '整体判断',
    reviewStarTitle: '这次打几分？',
    reviewTagsTitle: '这次最像什么体验？',
    reviewSubmitAction: '记录这次体验',
    reviewSavedNotice: '已记住这次体验',
    reviewCountLabel: '条体验',
    reviewEmptyLabel: '暂时还没有体验记录',
    voteOptions: {
      up: '下次还值得先拿出来',
      down: '下次别先拿这个',
    },
    stats: {
      recommendation: '推荐',
      opens: '打开',
      nativeCard: '站内道具',
      externalLink: '外部打开',
    },
  },
  profile: {
    title: '我的',
    subtitle: '账户信息与 DoraPocket 偏好设置。',
  },
  pocket: {
    title: '我的口袋',
    subtitle: '把账户信息、设置和我的工具都放回一个真正能用的“我的”页面。',
    searchPlaceholder: '搜索我的工具…',
    emptyTitle: '口袋里还没有工具',
    emptyDescription: '先去道具库看看，把你以后还想再打开的工具收进来。',
    goMarketAction: '去道具库找工具',
    backToAnalysisAction: '回到 Dora 出手',
    unpinAction: '取消常用',
    pinAction: '设为常用',
    unmarkPurchasedAction: '取消已购',
    markPurchasedAction: '标记已购',
    archiveAction: '归档',
    unarchiveAction: '取消归档',
    removeAction: '移出我的工具',
    deleteAction: '删除',
    pinnedBadge: '常用',
    purchasedBadge: '已购',
    pinnedSection: '常用工具',
    collectionSection: '我的工具',
    archivedSection: '归档',
    noSearchResult: '没有找到符合当前搜索条件的工具。',
  },
} as const

export const SETTINGS_COPY = {
  title: '设置',
  subtitle: '决定 DoraPocket 怎么陪你、怎么说、什么时候替你记住。',
  heading: '设置',
  description: '这些设置会同时影响 DoraPocket 怎么出手、怎么解释，以及哪些道具会进入系统决策。',
  sections: {
    companion: {
      title: '陪伴方式',
      description: '让 DoraPocket 更安静，或者更主动一点。',
    },
    memory: {
      title: '记住什么',
      description: '决定系统是否记录你的历史信号，帮助下一次判断更省事。',
    },
    presentation: {
      title: '怎么呈现',
      description: '决定它回答得更直接，还是保留更多为什么。',
    },
    reset: {
      title: '重置与清理',
      description: '当你想重新开始时，控制权仍在你手里。',
    },
  },
  items: {
    voicePlayback: {
      title: '语音播报',
      description: '结果出来后，要不要让 DoraPocket 用声音补一句。',
    },
    voicePlaybackMode: {
      title: '播报时机',
      description: '只播关键结论，还是播完整回答。',
      options: [
        { value: 'off', label: '保持安静' },
        { value: 'key-result', label: '只播结论' },
        { value: 'full', label: '完整播报' },
      ],
    },
    memory: {
      title: '记录历史帮助推荐',
      description: '允许系统记住你怎么选，减少下一次重复判断。',
    },
    builtinToolsEnabled: {
      title: '内置道具开关',
      description: '关闭后，系统会把内置道具视为不存在，不展示、不推荐，也不允许使用。',
    },
    explanationMode: {
      title: '解释详细度',
      description: '更快给结论，或者保留更多理由。',
      options: [
        { value: 'brief', label: '更直接' },
        { value: 'standard', label: '保留理由' },
      ],
    },
    fontPreset: {
      title: '阅读字体风格',
      description: '调整整体阅读气质，让信息更贴近你的浏览习惯。',
      options: [
        { value: 'a', label: '稳重' },
        { value: 'b', label: '利落' },
        { value: 'c', label: '轻快' },
        { value: 'd', label: '圆润' },
      ],
    },
  },
  actions: {
    resetPreferenceTitle: '重置推荐偏好',
    resetPreferenceDescription: '清空显式校准，让系统重新理解你的使用习惯。',
    resetPreferenceAction: '重置偏好',
    clearHistoryTitle: '清空对话历史',
    clearHistoryDescription: '删除已经保存的对话记录，但不会影响我的工具。',
    clearHistoryAction: '清空历史',
  },
} as const

export const SYSTEM_NOTICE_COPY = {
  savedForLater: '已保存为以后可直接打开的工具',
  analysisFailed: '这次出手失败了，请稍后再试',
} as const

export const VOICE_COPY = {
  started: '语音输入已开始',
  emptyTranscript: '没有听清内容。你也可以直接切回文字输入。',
  timeout: '监听超时，已自动结束。你也可以直接使用文字输入。',
  errors: {
    network: '语音识别依赖浏览器在线服务，网络异常时请改用文字输入。',
    'no-speech': '没有听清语音，请靠近麦克风后再试。',
    'not-allowed': '麦克风权限未开启，请在浏览器地址栏授权。',
    aborted: '语音识别已中断。',
    'audio-capture': '无法访问麦克风，可能被其他应用占用。',
    'service-not-allowed': '系统或浏览器禁用了语音识别服务。',
    'start-failed': '无法启动语音识别，请稍后再试或改用文字输入。',
  },
  fallbackErrorPrefix: '语音识别错误：',
} as const

export const MARKET_ACTIVITY_COPY = {
  feedbackUp: '投了好票',
  feedbackDown: '投了反对票',
  reviewUp: '补充了正向体验',
  reviewDown: '补充了负向体验',
  subscribed: '订阅了工具',
  unsubscribed: '取消了订阅',
  submitted: '提交了工具',
  reviewTags: {
    fast_to_start: '上手快',
    great_result: '结果好',
    chinese_friendly: '中文友好',
    no_login: '不用登录',
    beginner_friendly: '适合新手',
    time_saving: '省时间',
    worth_saving: '值得收进口袋',
    too_complex: '太复杂',
    needs_login: '需要登录',
    too_expensive: '太贵',
    average_result: '结果一般',
    unstable: '不够稳定',
    not_for_this_task: '不适合这次任务',
    high_learning_cost: '学习成本高',
  },
  summaries: {
    preferredCategoriesPrefix: '偏好',
    preferredCategoriesSuffix: '类工具',
    savedTagsPrefix: '常收',
    savedTagsSuffix: '相关能力',
    avoidAuthWall: '更偏好免登录、低摩擦工具',
    lowTrialCost: '对低试错成本工具更敏感',
    prefersSubscriptionTools: '愿意把工具沉淀成长线订阅资产',
  },
} as const
