export const APP_BRAND_TITLE = 'DoraPocket'

export const PAGE_COPY = {
  analysis: {
    title: APP_BRAND_TITLE,
    subtitle: '像哆啦A梦一样，在你开口时先替你挑出这次最该用的工具。',
    promptSuggestion: '帮我找一个最好用的 PDF 压缩工具',
    promptPlaceholder: '试试：帮我找一个最好用的 PDF 压缩工具',
    decisionSteps: [
      { step: 1, title: '从哪里开始' },
      { step: 2, title: '分析过程' },
      { step: 3, title: '推荐结果' },
    ],
    starter: {
      wizardEyebrow: '快速出手',
      step1Title: '什么身份最接近你？',
      step1Hint: '我们会按你的日常分工来收束推荐。',
      step2Title: '这次想完成什么？',
      step2Hint: '先选一个结果导向的目标；具体任务在下方操作区补充。',
      step3Title: '这次在意什么？',
      step3Hint: '从团队、收费、广告到上手体验，可多选，也可以先跳过。',
      intakeSummaryTitle: '出手前提',
      intakeSummaryHint: '基于你在「从哪里开始」的点选，DoraPocket 会按这些条件进入分析。',
      dockTaskLabel: '这次想完成什么？',
      dockTaskHint: '用一句话描述任务，至少 4 个字。',
      customTaskPlaceholder: '用自己的话描述任务，至少 4 个字…',
      nextToOutcome: '下一步：这次目标',
      nextToConstraints: '下一步：在意什么',
      backAction: '上一步',
      startAction: '开始分析',
      newTaskAction: '开始新任务',
      roleUnspecified: '未指定',
      noConstraints: '无特别约束',
      summaryRole: '身份',
      summaryGoal: '目标',
      summaryConstraints: '约束',
      actionsDisabledHint: '当前已有分析结果。想重新点选，请先开始新任务。',
    },
  },
  market: {
    title: '道具库',
    subtitle: '发现好工具、提交好工具，一起把 DoraPocket 的工具知识库养起来。',
    searchPlaceholder: '搜索工具、能力、标签或场景…',
    submitAction: '提交工具',
    collectAction: '收进口袋',
    openAction: '打开工具',
    reviewAction: '补充体验',
    reviewSupplementScore: '补充评分',
    updateReviewAction: '更新体验',
    pocketSection: '我的口袋',
    unavailableToolTitle: '工具已下架',
    unavailableToolDescription: '这件道具已不在道具库中，可以从口袋移出。',
    removeUnavailableAction: '移出口袋',
    removeFromPocketAction: '移出口袋',
    pocketEmptyTitle: '口袋里还没有工具',
    pocketEmptyDescription: '先去发现道具，把你以后还想再打开的工具收进来。',
    pocketEmptyAction: '去发现道具',
    discoverScopeLabel: '全部道具',
    discoverSection: '发现',
    noSearchResult: '没有找到符合当前搜索条件的工具。',
    reviewDrawerTitle: '这次这个工具好用吗？',
    reviewDrawerSubtitle: '告诉 DoraPocket 它为什么适合，或者为什么这次不该先掏出来。',
    reviewVoteTitle: '整体判断',
    reviewStarTitle: '这次打几分？',
    reviewTagsTitle: '这次最像什么体验？',
    reviewSubmitAction: '记录这次体验',
    reviewSavedNotice: '已记住这次体验',
    reviewCountLabel: '条体验',
    reviewEmptyLabel: '暂时还没有体验记录',
    voteOptions: {
      up: '下次还值得先拿出来',
      down: '下次别先拿这个',
    },
    stats: {
      recommendation: '推荐',
      opens: '打开',
      nativeCard: '站内道具',
      externalLink: '外部打开',
    },
  },
  profile: {
    title: '我的 Dora',
    subtitle: '任务记忆、偏好画像和 Dora 的陪伴方式。',
    compassTitle: 'Dora 任务罗盘',
    compassDescription: '从你的判断记录里整理任务方向，帮助 Dora 下次更快理解你。',
    memorySummaryTitle: 'Dora 目前这样理解你',
    memoryEmptyTitle: 'Dora 还没有足够记录',
    memoryEmptyDescription: '完成几次分析后，这里会整理出你的任务方向和偏好信号。',
    historyTitle: '判断记录',
    historyDescription: '每一次输入、输出和后续动作，都会沉淀成可回看的任务记忆。',
    historyEmptyTitle: '还没有判断记录',
    historyEmptyDescription: '去让 Dora 分析一次任务，这里会出现第一张任务票据。',
    historyError: '判断记录暂时加载失败，请稍后再试。',
    accountTitle: '账号',
    loginHint: '登录后才能同步任务记忆、设置和判断记录。',
    settingsTitle: 'Dora 怎么陪你',
    settingsDescription: '控制 Dora 如何记住历史、解释结果和使用声音。',
    allDirections: '全部',
    filters: {
      all: '全部',
      saved: '已收藏',
      evaluated: '已评价',
      lowConfidence: '低置信度',
    },
  },
  pocket: {
    title: '我的口袋',
    subtitle: '把账户信息、设置和我的工具都放回一个真正能用的“我的”页面。',
    searchPlaceholder: '搜索我的工具…',
    emptyTitle: '口袋里还没有工具',
    emptyDescription: '先去道具库看看，把你以后还想再打开的工具收进来。',
    goMarketAction: '去道具库找工具',
    backToAnalysisAction: '回到 Dora 出手',
    unpinAction: '取消常用',
    pinAction: '设为常用',
    unmarkPurchasedAction: '取消已购',
    markPurchasedAction: '标记已购',
    archiveAction: '归档',
    unarchiveAction: '取消归档',
    removeAction: '移出我的工具',
    deleteAction: '删除',
    pinnedBadge: '常用',
    purchasedBadge: '已购',
    pinnedSection: '常用工具',
    collectionSection: '我的工具',
    archivedSection: '归档',
    noSearchResult: '没有找到符合当前搜索条件的工具。',
  },
} as const

export const SETTINGS_COPY = {
  title: '设置',
  subtitle: '决定 DoraPocket 怎么陪你、怎么说、什么时候替你记住。',
  heading: '设置',
  description: '这些设置会同时影响 DoraPocket 怎么出手、怎么解释，以及哪些道具会进入系统决策。',
  sections: {
    companion: {
      title: '陪伴方式',
      description: '让 DoraPocket 更安静，或者更主动一点。',
    },
    memory: {
      title: '记住什么',
      description: '决定系统是否记录你的历史信号，帮助下一次判断更省事。',
    },
    presentation: {
      title: '怎么呈现',
      description: '决定它回答得更直接，还是保留更多为什么。',
    },
    reset: {
      title: '重置与清理',
      description: '当你想重新开始时，控制权仍在你手里。',
    },
  },
  items: {
    voicePlayback: {
      title: '语音播报',
      description: '结果出来后，要不要让 DoraPocket 用声音补一句。',
    },
    voicePlaybackMode: {
      title: '播报时机',
      description: '只播关键结论，还是播完整回答。',
      options: [
        { value: 'off', label: '保持安静' },
        { value: 'key-result', label: '只播结论' },
        { value: 'full', label: '完整播报' },
      ],
    },
    memory: {
      title: '记录历史帮助推荐',
      description: '允许系统记住你怎么选，减少下一次重复判断。',
    },
    explanationMode: {
      title: '解释详细度',
      description: '更快给结论，或者保留更多理由。',
      options: [
        { value: 'brief', label: '更直接' },
        { value: 'standard', label: '保留理由' },
      ],
    },
    fontPreset: {
      title: '阅读字体风格',
      description: '调整整体阅读气质，让信息更贴近你的浏览习惯。',
      options: [
        { value: 'a', label: '稳重' },
        { value: 'b', label: '利落' },
        { value: 'c', label: '轻快' },
        { value: 'd', label: '圆润' },
      ],
    },
  },
  actions: {
    resetPreferenceTitle: '重置推荐偏好',
    resetPreferenceDescription: '清空显式校准，让系统重新理解你的使用习惯。',
    resetPreferenceAction: '重置偏好',
    clearHistoryTitle: '清空对话历史',
    clearHistoryDescription: '删除已经保存的对话记录，但不会影响我的工具。',
    clearHistoryAction: '清空历史',
  },
} as const

export const STEP2_COPY = {
  expandEarlier: '展开 earlier ▾',
  lowConfidenceHint: '部分条件未确认，推荐置信度偏低。你可以返回 Step 2 补充。',
} as const

export const SYSTEM_NOTICE_COPY = {
  savedForLater: '已保存为以后可直接打开的工具',
  analysisFailed: '这次出手失败了，请稍后再试',
} as const

export const VOICE_COPY = {
  started: '语音输入已开始',
  emptyTranscript: '没有听清内容。你也可以直接切回文字输入。',
  timeout: '监听超时，已自动结束。你也可以直接使用文字输入。',
  errors: {
    network: '语音识别依赖浏览器在线服务，网络异常时请改用文字输入。',
    'no-speech': '没有听清语音，请靠近麦克风后再试。',
    'not-allowed': '麦克风权限未开启，请在浏览器地址栏授权。',
    aborted: '语音识别已中断。',
    'audio-capture': '无法访问麦克风，可能被其他应用占用。',
    'service-not-allowed': '系统或浏览器禁用了语音识别服务。',
    'start-failed': '无法启动语音识别，请稍后再试或改用文字输入。',
  },
  fallbackErrorPrefix: '语音识别错误：',
} as const

export const MARKET_ACTIVITY_COPY = {
  feedbackUp: '投了好票',
  feedbackDown: '投了反对票',
  reviewUp: '补充了正向体验',
  reviewDown: '补充了负向体验',
  subscribed: '订阅了工具',
  unsubscribed: '取消了订阅',
  submitted: '提交了工具',
  reviewTags: {
    fast_to_start: '上手快',
    great_result: '结果好',
    chinese_friendly: '中文友好',
    no_login: '不用登录',
    beginner_friendly: '适合新手',
    time_saving: '省时间',
    worth_saving: '值得收进口袋',
    too_complex: '太复杂',
    needs_login: '需要登录',
    too_expensive: '太贵',
    average_result: '结果一般',
    unstable: '不够稳定',
    not_for_this_task: '不适合这次任务',
    high_learning_cost: '学习成本高',
  },
  summaries: {
    preferredCategoriesPrefix: '偏好',
    preferredCategoriesSuffix: '类工具',
    savedTagsPrefix: '常收',
    savedTagsSuffix: '相关能力',
    avoidAuthWall: '更偏好免登录、低摩擦工具',
    lowTrialCost: '对低试错成本工具更敏感',
    prefersSubscriptionTools: '愿意把工具沉淀成长线订阅资产',
  },
} as const
